# === templates-base ===========================================================
[files]
extend-exclude = ["*.lock", "LICENSES/", "CHANGELOG.md"]
# === end templates-base =======================================================
